### ISSUE TITLE
port and auto_reconnect option not accepted in YAML

### ISSUE THREAD

**Issue by legnad** [grimmpp/home-assistant-eltako#124]
`port `and `auto_reconnect` option not accepted in YAML with the result of the Integration not loading.

![grafik](https://github.com/user-attachments/assets/d5c4f7b7-0721-4ebd-a4ab-d4e21a0bdb2a)

YAML:
```
  gateway:
...
  - id: 2
    base_id: FF-9F-5E-80 # PioTek FAM-USB 515 # /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0P4TMI-if00-port0
    #device_type: "enocean-usb300"
    serial_path: "192.168.2.7"
    device_type: "mgw-lan"
    address: 192.168.2.7
    port: 5100
    auto_reconnect: False
    devices:
...
```

![grafik](https://github.com/user-attachments/assets/77b94438-46dd-436f-8dad-19f3535fe262)

Reference: #121
