### ISSUE TITLE
Climate Component Not Controlling FHK14 Valve

### ISSUE THREAD

**Issue by Simon-Says-eng** [grimmpp/home-assistant-eltako#137]
Description

Last week, I found your project and was very impressed with how smoothly the integration with my system worked. However, one remaining issue involves the FHK14 modules.

The climate component in my test setup is not functioning as expected. The Home Assistant GUI displays the thermostat's temperature and updates its value when I change it. However, despite setting the target temperature to 28°C while the current temperature is 13°C, the valve does not respond. The FHK14 module blinks briefly every three minutes, but the valve remains unmoved.

Additionally, I tried using a 4-key switch, but it does not trigger any further action either.
Default open or default closed option in PCT14 does also change nothing
Test Setup

Here is my current configuration:

```
eltako:
  gateway:
    - id: 1
      base_id: FF-B8-DA-00
      device_type: fgw14usb
      devices:
        light:
          - id: 00-00-00-07
            eep: M5-38-08
            name: "FSR14_4x - 3"
            sender:
              id: FF-D7-C5-87
              eep: A5-38-08
          - id: 00-00-00-08
            eep: M5-38-08
            name: "FSR14_4x - 4"
            sender:
              id: FF-D7-C5-88
              eep: A5-38-08
        binary_sensor:
          - id: fe-d5-4c-9b
            eep: F6-02-01
        cover:
          - id: 00-00-00-09
            eep: G5-3F-7F
            name: FSB14 - 6
            sender:
              id: FF-D7-C5-91
              eep: H5-3F-7F
            device_class: shutter
            time_closes: 24
            time_opens: 25
        climate:
          - id: 00-00-00-29
            name: "Unbekannt"
            eep: A5-10-06               # Telegram type of the actuator (1)
            temperature_unit: "°C"      # Displayed temperature unit in Climate Panel (2)
            min_target_temperature: 9  # Optional field, default value 17 (2)
            max_target_temperature: 25  # Optional field, default value 25 (2)
            sender:                     # Virtual temperature controller (2)
              id: FF-D7-C5-30           # Sender address (2) needs to be entered
              eep: A5-10-06             # Sender EEP
            thermostat:
              id: 05-2B-4F-EB
              eep: A5-10-06
          - id: 00-00-00-22
            eep: A5-10-06               # Telegram type of the actuator (1)
            name: "EG WC"
            temperature_unit: "°C"      # Displayed temperature unit in Climate Panel (2)
            min_target_temperature: 10  # Optional field, default value 17 (2)
            max_target_temperature: 25  # Optional field, default value 25 (2)
            sender:                     # Virtual temperature controller (2)
              id: FF-D7-C5-11           # Sender address (2) needs to be entered
              eep: A5-10-06             # Sender EEP
            thermostat:
              id: 05-2B-5F-D8
              eep: A5-10-06
```

Observations
    The FHK14 module blinks every three minutes but does not move the valve.
    The Home Assistant GUI correctly displays the temperature and updates when I change the value.
    The 4-key switch also fails to trigger any valve action.

Questions
    Is there a way to test the valve using PCT14?
    Are there additional steps required to ensure the FHK14 module responds correctly?

Additional Information
    Current temperature: 13°C
    Target temperature: 28°C
    Hardware: FHK14 module
    Gateway: FGW14USB

Any insights or guidance on resolving this issue would be greatly appreciated!
