### ISSUE TITLE
FAM 14 + USB 300

### ISSUE THREAD

**Issue by kmidt** [grimmpp/home-assistant-eltako#149]
Hello everyone,

I have a FAM 14 with over 32 devices. I was able to read it perfectly with a laptop and a USB cable using the tool here.
I entered everything into the config and devices are there. I can't control it because I don't have my home assistant connected to the FAM.
To date I have always used FHEM with a USB 300.

How do I get the Homeassistant to communicate with the USB 300 and the FAM 14 and I can use the devices in the HA?

Must i teach in the devices ? 

Thank you and greetings,
Andi

**Comment by matr1z** [comment]
Hi Andi,

In my house I am operating two FAM14 based Eltako systems. One system is connected via FGW14-USB, but the other one is operating through a USB 300 (because I have not managed to operate two instances of FGW14-USB in one Eltako integration).

Here is the respective section of my configuration.yaml for the USB 300:

```
eltako:
  general_settings:
    fast_status_change: False
    show_dev_id_in_dev_name: True

  gateway:
    - id: 1
      device_type: enocean-usb300
      base_id: FF-XX-XX-00 # baseId of USB300 gateway #
```
After this the section "devices:" section follows. Please note that with a wireless connection (like with the USB-300) the device IDs are a sum of the BaseID of your FAM14 and the address of the respective Eltako device. 
So, if your FAM14 has a base ID of FF-12-34-80 and you have an Eltako device added with the address 01, then that device will have the ID FF-12-34-81 = FF-12-34-80 + 01.

Once you have everything configured, you should be able to activate the integration. For this go to Settings -> Devices -> Eltako -> "ADD HUB".  In the upcoming dialog you will then select your USB 300.

Hope this helps.

Martin
