### ISSUE TITLE
Device cannot be deleted. Link / Button to delete is missing.

### ISSUE THREAD

**Issue by LHBL2003** [grimmpp/home-assistant-eltako#42]
### Problem:
A single device cannot be deleted. The entire integration must be deleted to remove a device. However, the deletion of individual devices is supported by Google Case TV, for example.

---------------------------------------------------------------------------------------------

### Change request
Please create a delete button for the individual devices. 

<img width="1918" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/4e4b3c21-a0fc-4ad2-8bd4-4724074c0079">

---------------------------------------------------------------------------------------------

### To recreate the problem:

-  **Create a Dummy in Eltako Config**

```
          #----------------------------------------------------------------------
          #Dummy
          - id: FE-00-00-50
            eep: M5-38-08
            name: DUMMY
            sender:
              id: FD-00-00-50
              eep: F6-02-01
```

<img width="927" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/b8400986-c291-402d-8524-15343d9f3cd1">

- Check HA Config and Restart
- The dummy is available

<img width="1309" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/a2917982-285f-4b35-893f-e495615ab55b">

- Remove or Deactivate Dummy in Config and Restart HA

<img width="1135" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/d8f550c0-3ae9-48da-97e6-b0006029b19b">

- Go to the entity and delete it (It is possible to delete the entity for the device.)

<img width="457" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/3f3e9002-4010-43a3-8da0-a03e88dce0b9">

<img width="453" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/b16a73ed-c468-4cbb-a96f-7986546574a7">

- Try to delete the device

<img width="1918" alt="image" src="https://github.com/grimmpp/home-assistant-eltako/assets/46369917/7428611e-bdca-4db4-9574-058cf023e3ec">
